### ISSUE TITLE
Document ADT (adt.csv) and cross-reference (xref.csv) tables in Tensorization.md

### ISSUE THREAD

**Issue by erikr** [aguirre-lab/ml4c3-wiki#107]

**Comment by erikr** [comment]
> @contactadityag: Also if you have any details regarding the differences between room_bed and BedLabelNM column that will be really helpful. Also it will be really helpful if there can be a one line description of what information these columns are trying to capture: https://github.com/aguirre-lab/ml4c3-wiki/issues/103

This issue is still backlogged. The rest of the team has other priorities right now, but I definitely think this information is important. I'll try to get to it next week.

That said, I think `room_bed` and `BedLabelNM` are redundant. What is your assessment? Can you also check which column is required by the pipeline?

It would be fantastic if you revise the pipeline to not create or use the redundant column, and [submit a PR](https://github.com/aguirre-lab/ml4c3/blob/master/CONTRIBUTING.md#rocket-pull-requests).

I also deleted the other issue that I created which you referenced. I consolidated the scope into this issue, since `adt.csv` and `xref.csv` are somewhat related.

**Comment by contactadityag** [comment]
Hi @erikr, No worries. Please take your time. I am working on this issue and I will definitely keep you updated regarding my findings.

**Comment by erikr** [comment]
Aditya, thanks for your patience. For context I have to generate some results for this cardiac surgery project ([link to board](https://github.com/orgs/aguirre-lab/projects/3), Ridwan is moving, and the rest of the team has masters theses to focus on right now.

**Comment by erikr** [comment]
@raimonpv I know I've tagged you in a lot of GitHub issues and discussions today! But if you have any time, do you think you could help with this? I ask because the columns of `xref.csv` are fresh in your mind given you just worked on https://github.com/aguirre-lab/ml4c3/pull/1219. Let me know if there are other tasks others can help you with, or if you need to backlog some things. Thanks for considering.
