### ISSUE TITLE
Update Visualizer documentation

### ISSUE THREAD

**Issue by erikr** [aguirre-lab/ml4c3-wiki#112]
Update [documentation](https://github.com/aguirre-lab/ml4c3/wiki/Visualizer) to reflect the new token auth method.

**Comment by epalto** [comment]
Blocked for the moment by the PR and discussion on aguirre-lab/ml4c3#1104

**Comment by erikr** [comment]
[The options file example](https://github.com/aguirre-lab/ml4c3/wiki/Visualizer#options-file) you provided is clear and thorough. Great work!

A few questions that would be helpful to clarify on that page:

1. Is this file generated by the visualizer app?
2. Is this arg optional?
3. Is there a required extension, or should the file be extentionless, e.g. `--options_file /path/to/visualizer_options`?
